-- 1

SELECT SUM(quantity) AS TotalProducts_Sold
FROM ECOMMERCE
WHERE "PURCHASE_DATE" LIKE '2019-02%';

-- 2

SELECT SUBSTR("PURCHASE_DATE",1,4) AS "Year", 
SUM(price * Quantity) AS TotalSalesAmount
FROM ECOMMERCE
GROUP BY SUBSTR("PURCHASE_DATE",1,4);

-- 3


SELECT 
SUBSTR("PURCHASE_DATE",6,2) AS "Month",
productno,
SUM(price * Quantity) AS TotalSalesAmount
FROM ECOMMERCE
WHERE SUBSTR("PURCHASE_DATE",1,4)='2019'
GROUP BY productno, 
SUBSTR("PURCHASE_DATE",6,2);


--4

SELECT Country, COUNT(DISTINCT customerno) AS customer_count
FROM ECOMMERCE
GROUP BY COUNTRY;

--5

SELECT DISTINCT PRODUCTNAME AS UNIQUE_PRODUCTS, 
SUBSTR("PURCHASE_DATE",1,4) AS "Year"
FROM ECOMMERCE;